[build]
  base = "skillsphere-frontend"
  publish = "dist/skillsphere-frontend"
  command = "npm install && npm run build -- --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
